FROM node:22-alpine AS base
RUN apk add --no-cache libc6-compat openssl
RUN npm install -g pnpm

FROM base AS web
WORKDIR /app/web

COPY ./web/package.json ./web/pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY ./web ./

EXPOSE 5173
CMD ["pnpm", "run", "dev"]

FROM base AS server
WORKDIR /app/server

COPY ./server/package.json ./server/pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY ./server ./

RUN pnpm run db:generate --schema ./prisma/schema.prisma

EXPOSE 3000
CMD ["pnpm", "run", "dev"]
