services:
  database:
    image: postgres:16
    container_name: nest_database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/usr/app/data/postgres_data
    networks:
      - app_network

  s3:
    image: minio/minio:latest
    container_name: nest_s3
    restart: always
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    command: server /data --console-address ":9001"
    ports:
      - "${S3_PORT}:9000"
      - "9001:9001"
    volumes:
      - s3_data:/usr/app/data/s3_data
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    container_name: nest_redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/usr/app/data/redis_data
    networks:
      - app_network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: nest_redis-commander
    environment:
      REDIS_HOSTS: "local:${REDIS_HOST}:${REDIS_PORT}"
    ports:
      - "8081:8081"
    depends_on:
      - redis

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: nest_server
    restart: "on-failure"
    ports:
      - "${NEST_PORT}:3000"
    env_file:
      - .env
    depends_on:
      - database
      - redis
      - s3
    networks:
      - app_network

volumes:
  postgres_data:
  s3_data:
  redis_data:

networks:
  app_network:
    driver: "bridge"