services:
  nginx:
    image: nginx:alpine
    container_name: app_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
      - web
    networks:
      - app_network

  database:
    image: postgres:16-alpine
    container_name: nest_database
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "catalog-app"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  s3:
    image: minio/minio:latest
    container_name: nest_s3
    restart: always
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "12345678"
    command: server /data --console-address ":9001"
    ports:
      - "900:9000"
      - "9001:9001"
    volumes:
      - s3_data:/data
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    container_name: nest_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: server
    container_name: nest_server
    restart: always
    env_file:
      - .env
    depends_on:
      - database
      - redis
      - s3
    develop:
      watch:
        - path: ./server/src
          target: /app/server/src
          action: sync
          ignore:
            - ./server/node_modules
            - ./server/prisma
            - ./server/dist
            - ./server/tmp
            - ./server/package-lock.json
            - ./server/pnpm-lock.yaml
        - path: ./server/package.json
          action: rebuild
    networks:
      - app_network

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: web
    container_name: react_web
    restart: always
    env_file:
      - .env
    develop:
      watch:
        - path: ./web/src
          target: /app/web/src
          action: sync
          ignore:
            - ./web/node_modules
            - ./web/package.json
            - ./web/.vite
            - ./web/tmp
            - ./web/coverage
        - path: ./web/package.json
          action: rebuild
    networks:
      - app_network

volumes:
  postgres_data:
  s3_data:
  redis_data:

networks:
  app_network:
    driver: bridge