FROM node:22-alpine
RUN apk add --no-cache libc6-compat openssl
RUN npm install -g pnpm

WORKDIR /app/server
COPY ./server/package.json ./server/pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY ./server .

RUN pnpm run db:generate --schema ./server/prisma/schema.prisma

EXPOSE 3000
CMD ["pnpm", "run", "dev"]
