type Game {
  id: String!
  rawgId: Int!
  name: String!
  isCompleted: Boolean!
  description: String
  backgroundImage: String
  rating: Float!
  released: DateTime
  esrbRating: EsrbRating
  genres: [String!]!
  platforms: [String!]!
}

"""
A date-time string at UTC, such as 2019-12-03T09:54:33Z, compliant with the date-time format.
"""
scalar DateTime

enum EsrbRating {
  EVERYONE
  EVERYONE_10_PLUS
  TEEN
  MATURE
  ADULTS_ONLY
  RATING_PENDING
}

type PartialGame {
  id: String!
  name: String!
  isCompleted: Boolean!
  backgroundImage: String
  rating: Float!
  esrbRating: EsrbRating
  genres: [String!]!
  platforms: [String!]!
}

type PaginatedGames {
  data: [PartialGame!]!
  totalCount: Int!
  totalPages: Int!
  hasNextPage: Boolean!
}

type RawgGame {
  rawgId: Float!
  name: String!
  backgroundImage: String
}

type PaginatedRawgGames {
  data: [RawgGame!]!
  totalCount: Int!
  totalPages: Int!
  hasNextPage: Boolean!
}

type PaginatedPlatforms {
  data: [String!]!
  totalCount: Int!
  totalPages: Int!
  hasNextPage: Boolean!
}

type PaginatedGenres {
  data: [String!]!
  totalCount: Int!
  totalPages: Int!
  hasNextPage: Boolean!
}

type UserCatalogItem {
  id: String!
  name: String!
  image: String!
  description: String
}

type PaginatedItems {
  data: [UserCatalogItem!]!
  totalCount: Int!
  totalPages: Int!
  hasNextPage: Boolean!
}

type User {
  id: String!
  username: String
  email: String!
}

type Query {
  getUser(input: GetUserInput!): User
  getAllItems(input: GetAllItemsInput): PaginatedItems!
  getItemById(id: String!): UserCatalogItem
  getAllGames(input: GetAllGamesInput!, filter: GetAllGamesFilterInput): PaginatedGames!
  getGameById(id: String!): Game
  getRawgGames(input: GetRawgGamesInput!): PaginatedRawgGames!
  getAllPlatforms(input: GetAllPlatformsInput!): PaginatedPlatforms!
  getAllGenres(input: GetAllGenresInput!): PaginatedGenres!
}

input GetUserInput {
  email: String!
}

input GetAllItemsInput {
  page: Int!
  pageSize: Int!
}

input GetAllGamesInput {
  page: Int!
  pageSize: Int!
}

input GetAllGamesFilterInput {
  name: String
  rating: Float
  isCompleted: Boolean!
  genres: [String!]
  platforms: [String!]
  esrbRating: EsrbRating
}

input GetRawgGamesInput {
  page: Int!
  pageSize: Int!
  search: String
}

input GetAllPlatformsInput {
  page: Int!
  pageSize: Int!
}

input GetAllGenresInput {
  page: Int!
  pageSize: Int!
}

type Mutation {
  registerUser(input: RegisterUserInput!): User
  authorizeUser(input: AuthorizeUserInput!): User
  signOut: Boolean!
  updateUser(input: UpdateUserInput!): User!
  deleteUser(input: DeleteUserInput!): User!
  createItem(input: CreateItemInput!, image: Upload!): UserCatalogItem!
  updateItem(input: UpdateItemInput!, image: Upload!): UserCatalogItem!
  deleteItem(id: String!): UserCatalogItem!
  updateGame(input: UpdateGameInput!): Game!
  deleteGame(id: String!): Game!
  createGame(id: Float!): Game!
}

input RegisterUserInput {
  email: String!
  password: String!
}

input AuthorizeUserInput {
  email: String!
  password: String!
}

input UpdateUserInput {
  username: String
}

input DeleteUserInput {
  password: String!
}

input CreateItemInput {
  name: String!
  description: String
}

"""The `Upload` scalar type represents a file upload."""
scalar Upload

input UpdateItemInput {
  id: String!
  name: String
  description: String
}

input UpdateGameInput {
  id: String!
  isCompleted: Boolean!
}